export {default as Header} from './Header/Header'
export {default as Home} from './Home/Home'
export {default as Services} from './Services/Services'
export {default as About} from './About/About'
export {default as Portfolio} from './Portfolio/Portfolio'
export {default as Contact} from './Contact/Contact'
export {default as Footer} from './Footer/Footer'
// export {default as Container} from './Container/Container'